### ISSUE TITLE
Change "Nu School Breaks" to "Nu Skool Breaks"

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1306]
slurp docs site menu item.  Also rename file

<img width="160" alt="Screen Shot 2022-01-13 at 6 57 37 pm" src="https://user-images.githubusercontent.com/418747/149298499-9305a0cf-9d76-481c-bd6e-fa8c5526874b.png">

**Comment by devnikesh** [comment]
Hi @jbampton assign me the task, I can get it done.

**Comment by jbampton** [comment]
Thanks mate 👍 

https://en.wikipedia.org/wiki/Nu_skool_breaks

**Comment by devnikesh** [comment]
@jbampton I've renamed and opened a PR.

**Comment by jbampton** [comment]
Thanks.  I sent you an invite to our Org 👍

**Comment by devnikesh** [comment]
@jbampton  Joined, Thank you. 😄

**Comment by jbampton** [comment]
Done thank you !!
