### ISSUE TITLE
Docs need standardization

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1562]
<img width="424" alt="Screen Shot 2022-04-07 at 12 47 48 pm" src="https://user-images.githubusercontent.com/418747/162110588-2730fe93-ded1-4257-b82f-d6ad29be9d98.png">

**Comment by ihasidul** [comment]
Should all the lines be "About The Author"?

**Comment by jbampton** [comment]
@slurpcode/maintainers  what do you think ?

**Comment by smriad** [comment]
> @slurpcode/maintainers what do you think ?

First letter upper case and others are lower looks good

**Comment by ihasidul** [comment]
But for the main titles different 

> > @slurpcode/maintainers what do you think?
> 
> First letter upper case and others are lower looks good

After searching for standard title formatting I found that the formatting shown in the attached image is more accepted and widely used.  For example "The Battle Of Al-Latrun". Wouldn't it be better to follow that format for the rest of the titles for consistency? 
![image](https://user-images.githubusercontent.com/32800356/162484627-a4d6243c-e0fe-4d76-a9d5-d90752027819.png)

**Comment by BaseMax** [comment]
Thank you for sharing. good info

**Comment by BaseMax** [comment]
I learned something new from you.
respectability

**Comment by jis0324** [comment]
@jbampton I recommend @ihasidul 's suggestion :)

**Comment by BaseMax** [comment]
Hey @jis0324, What up? everything is fine there?

**Comment by BaseMax** [comment]
> @jbampton I recommend @ihasidul 's suggestion :)

Agree

**Comment by jis0324** [comment]
> Hey @jis0324, What up? everything is fine there?

Hello @BaseMax 
Yeah, I am good. thanks.
How about your life? 😄

**Comment by jis0324** [comment]
hah... @jbampton  don't react 👀 
I also wanted to ask your regards... 😄 
Hope and Hope you were doing well.

**Comment by BaseMax** [comment]
> How about your life? 😄

Thanks, I am fine. it's **Ramadan** here.

**Comment by jbampton** [comment]
Hey @jis0324  I am well thanks !!

Good to hear from you 👍

**Comment by jbampton** [comment]
I was eating popcorn :)

**Comment by BaseMax** [comment]
> <img alt="Screen Shot 2022-04-07 at 12 47 48 pm" width="424" src="https://user-images.githubusercontent.com/418747/162110588-2730fe93-ded1-4257-b82f-d6ad29be9d98.png">

John looks at things deeply with High microscopic accuracy.

**Comment by BaseMax** [comment]
It's why john helped most top organizations. like apache, ruby, and many more big projects. You can see the statistics.

**Comment by jbampton** [comment]
Hey @jis0324  this is popcorn 

![popcorn](https://user-images.githubusercontent.com/418747/162488127-1a2124dc-9ed8-40d1-9dad-7de11e069f3d.jpeg)

**Comment by jis0324** [comment]
lmao.. do you also like this???
I like this... just no time, so did not buy... 😢

**Comment by jbampton** [comment]
The box of popcorn was half price so I bought it 👍

**Comment by jis0324** [comment]
Well done 👍

**Comment by smriad** [comment]
https://arcticicestudio.github.io/styleguide-markdown/rules/headings.html

https://arcticicestudio.github.io/styleguide-markdown/rules/naming-conventions.html#file-naming

**Comment by HadeerAIA** [comment]
> @jbampton I recommend @ihasidul 's suggestion :)

This is a good one, Agree too.

**Comment by HadeerAIA** [comment]
> https://arcticicestudio.github.io/styleguide-markdown/rules/headings.html
> 
> https://arcticicestudio.github.io/styleguide-markdown/rules/naming-conventions.html#file-naming

These two links are helpful, especially in naming conventions, I was thinking it makes no change in naming, but now I think we can follow some rules from here too.

**Comment by jbampton** [comment]
Please go ahead @ihasidul with the `title case` for the `About the Author` heading 👍

**Comment by ihasidul** [comment]
Ok I am on it.

**Comment by jbampton** [comment]
Done thanks !!
