### ISSUE TITLE
Standardize the Docs files/folders names `-` & `_`

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1564]
<img width="368" alt="Screen Shot 2022-04-07 at 8 18 26 am" src="https://user-images.githubusercontent.com/418747/162119200-f4dfc91c-ddd8-4bc7-97e6-e96972e64ad5.png">

**Comment by ihasidul** [comment]
Is spinal-case being used for the naming convention?

**Comment by HadeerAIA** [comment]
> 

Yes, we used here spinal-case until now.
