### ISSUE TITLE
Circle CI well-formed error

### ISSUE THREAD

**Issue by smriad** [slurpcode/slurp#1593]
<img width="1280" alt="Screen Shot 2022-04-09 at 5 16 02 AM" src="https://user-images.githubusercontent.com/21966124/162545637-20ea22e1-00a7-4329-910f-932f38a9e025.png">

**Comment by smriad** [comment]
Fixed with PR https://github.com/slurpcode/slurp/pull/1602

<img width="1280" alt="Screen Shot 2022-04-09 at 10 57 16 AM" src="https://user-images.githubusercontent.com/21966124/162557089-74b7d2de-2266-450c-b405-d52df0d4020d.png">

**Comment by jbampton** [comment]
Done
