### ISSUE TITLE
Cicle CI Jekyll error

### ISSUE THREAD

**Issue by smriad** [slurpcode/slurp#1601]
<img width="1280" alt="Screen Shot 2022-04-09 at 10 35 08 AM" src="https://user-images.githubusercontent.com/21966124/162556514-9a3b2653-06e3-41a6-8980-078f7a2b313c.png">

We might need to downgrade ruby version in cirleci/config

https://talk.jekyllrb.com/t/cant-read-csv-file/5981

**Comment by BaseMax** [comment]
https://talk.jekyllrb.com/t/upgrade-to-ruby-3-tutorial/6113

**Comment by jbampton** [comment]
Fixed by #1628
