### ISSUE TITLE
Make scrapers/python/scrapy/github/spider.py more precise.

### ISSUE THREAD

**Issue by ihasidul** [slurpcode/slurp#1654]
Currently, the spider script only prints the title of the stats. Which misses some edge cases for example 1K. Make it more precise. print out the actual value for example 1,018.

**Comment by saqibur** [comment]
Is this being worked on?

**Comment by ihasidul** [comment]
No, you can work on it. @saqibur

**Comment by ihasidul** [comment]
@saqibur  Should I assign this story to you?

**Comment by jbampton** [comment]
Done
