### ISSUE TITLE
Add Aruba

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1836]
https://slurp.readthedocs.io/en/latest/

[Aruba1.docx](https://github.com/slurpcode/slurp/files/9655683/Aruba1.docx)

Author is Idais

**Comment by jbampton** [comment]
Hey @Vishrut19 how about this one ?

**Comment by Vishrut19** [comment]
Okay I just want to know that in this issue whatever it is there in the docs I have to just add it to your website. That's it right ?

**Comment by jbampton** [comment]
Correct.  They have been many similar PRs merged today

**Comment by Vishrut19** [comment]
okay can you please assign me this issue ?

**Comment by jbampton** [comment]
Good to go 💯

**Comment by Vishrut19** [comment]
Cool ! Thanks!
