### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1838]
<img width="642" alt="Screen Shot 2022-09-29 at 3 22 39 am" src="https://user-images.githubusercontent.com/418747/192848460-f7caf13a-1f3f-4701-84c9-52b64534530b.png">

**Comment by jbampton** [comment]
https://github.com/slurpcode/slurp/actions/runs/3145463524/jobs/5112783813

**Comment by mve** [comment]
It seems the link has changed, updated it in this PR:
https://github.com/slurpcode/slurp/pull/1839

**Comment by jbampton** [comment]
Done thanks !!
