### ISSUE TITLE
Standardize the `images` folders for our `doc`

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1857]
https://github.com/slurpcode/slurp/tree/main/doc/source/_static/images

I think we want to change `_` to `-` like how all the `source` Markdown files are

**Comment by semi-infiknight** [comment]
please assign me this

**Comment by jbampton** [comment]
Awesome let's go 💯

**Comment by semi-infiknight** [comment]
i didnt understand the issue completly tho

**Comment by jbampton** [comment]
We need to make all the "folders" with the same naming style.  For example in the image `_` should be changed to `-`

<img width="315" alt="Screen Shot 2022-10-01 at 11 26 24 am" src="https://user-images.githubusercontent.com/418747/193377798-b3c1a150-67ed-4b95-bc26-9209fceae73e.png">

**Comment by semi-infiknight** [comment]
okay done

**Comment by jbampton** [comment]
But also the Markdown files use these images so they need updating too.

**Comment by jbampton** [comment]
You are now assigned @Vishrut19

**Comment by janus** [comment]
@jbampton  If this issue is still open, I would like to work on it.

**Comment by jbampton** [comment]
Hey @janus good to go 👍
