### ISSUE TITLE
Broken links: configure link checker

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1862]

**Comment by jbampton** [comment]
https://github.com/slurpcode/slurp/actions/runs/4510398786/jobs/7941299403?pr=2099

**Comment by jbampton** [comment]
Hey @Dxuian can you just comment on this issue so that I can assign you to it ?

**Comment by Dxuian** [comment]
please assign to me @johnbampton

**Comment by jbampton** [comment]
Done thanks
