### ISSUE TITLE
Add Costa Rica

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1863]
[Costa_Ric1.docx](https://github.com/slurpcode/slurp/files/9689451/Costa_Ric1.docx)

https://slurp.readthedocs.io/en/latest/index.html

Author is Idais

**Comment by inomag** [comment]
Hi, can I work on this?

**Comment by jbampton** [comment]
Good to go 👍

**Comment by Vishrut19** [comment]
Hi @jbampton and @inomag  if you are working on it then its fine or can i work on it ?

**Comment by jbampton** [comment]
Oh I see now

**Comment by Vishrut19** [comment]
Can i take it ? @jbampton

**Comment by jbampton** [comment]
@Vishrut19 you are now assigned 👍
