### ISSUE TITLE
Can we use the All Contributors bot without emoji ?

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1865]
https://allcontributors.org/

refs #1864 

The idea is to remove all the emoji since it is hard to track what has been done

**Comment by TheLearneer** [comment]
You mean something like this below?

@all-contributors please add @TheLearneer for ideas

**Comment by jbampton** [comment]
No I don't want any emoji.

**Comment by TheLearneer** [comment]
You don't want the emoji in the readme file?

**Comment by jbampton** [comment]
Correct.  I want to remove all the emoji from everyone.

It is too much trouble tracking them and who does what.  Too much effort

**Comment by TheLearneer** [comment]
I don't think if we can achieve it with `allContributors` as of now.

**Comment by jbampton** [comment]
What are some other options.

Is there something similar ?

**Comment by TheLearneer** [comment]
I found this: https://github.com/ropenscilabs/allcontributors
But I am not sure how this will play along for our use-case.

**Comment by jbampton** [comment]
How about something like Lucee ?

https://github.com/lucee/Lucee#contributors

**Comment by TheLearneer** [comment]
LGTM
