### ISSUE TITLE
Add Qatar

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1867]
[Qatar1.docx](https://github.com/slurpcode/slurp/files/9689491/Qatar1.docx)

https://slurp.readthedocs.io/en/latest/index.html

Author is Idais

**Comment by bindu-r02** [comment]
@jbampton - Can I work on this

**Comment by jbampton** [comment]
Good to go mate 💯

**Comment by Vishrut19** [comment]
Hey! @jbampton can i work on this ?
