### ISSUE TITLE
Add Heidelberg

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1868]
[Heidelber1.docx](https://github.com/slurpcode/slurp/files/9689533/Heidelber1.docx)

https://slurp.readthedocs.io/en/latest/index.html

Author is Idais

**Comment by rashmisubhash** [comment]
Can I work on this

**Comment by Vishrut19** [comment]
Can I work on this ? @jbampton

**Comment by jbampton** [comment]
You will have to get one pr merged first before I assign another.

**Comment by Vishrut19** [comment]
Hey I want to work on this issue. Please assign me @jbampton

**Comment by jbampton** [comment]
Good to go @Vishrut19

**Comment by Vishrut19** [comment]
okay @jbampton I will do it
