### ISSUE TITLE
Add Rio de Janeiro

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1870]
[Rio_de_Janeiro.docx](https://github.com/slurpcode/slurp/files/9689546/Rio_de_Janeiro.docx)

https://slurp.readthedocs.io/en/latest/index.html

Author is Idais

**Comment by ry-v1** [comment]
Hello @jbampton, Can I work on this

**Comment by jbampton** [comment]
Good to go thanks 💯
