### ISSUE TITLE
Add Bucaramanga

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1874]
[Bucaramang1.docx](https://github.com/slurpcode/slurp/files/9689608/Bucaramang1.docx)

https://slurp.readthedocs.io/en/latest/index.html

Author is Idais

**Comment by rashmisubhash** [comment]
Can I take this up?

**Comment by jbampton** [comment]
How about you get one pr merged first ?

**Comment by rashmisubhash** [comment]
I have raised one

**Comment by island-coder** [comment]
Is it possible to work on this?

**Comment by jbampton** [comment]
You are now assigned @island-coder 👍
