### ISSUE TITLE
Add Santiago de Compostela

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1877]
[Santiago_de_Compostel1.docx](https://github.com/slurpcode/slurp/files/9689649/Santiago_de_Compostel1.docx)

https://slurp.readthedocs.io/en/latest/index.html

Author is Idais

**Comment by Vishrut19** [comment]
I want to work on this @jbampton ?

**Comment by jbampton** [comment]
You will have to get one pr merged first before I assign another.

**Comment by Vishrut19** [comment]
okay okay got it thanks for letting me know @jbampton

**Comment by island-coder** [comment]
@jbampton can I work on this? My previous PR was merged.

**Comment by jbampton** [comment]
Hey @island-coder you are now assigned 👍
