### ISSUE TITLE
Add Warsaw

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1878]
[Warsaw.docx](https://github.com/slurpcode/slurp/files/9689683/Warsaw.docx)

https://slurp.readthedocs.io/en/latest/index.html

Author is Idais

**Comment by mehraankush** [comment]
i can do that as well .. please assign it to me

**Comment by jbampton** [comment]
You will need to get one pr merged first before I assign another.  Thanks

**Comment by Kevan-Y** [comment]
Can I work on this one?

**Comment by Vishrut19** [comment]
Hey @jbampton I am taking this issue. Please assign me
