### ISSUE TITLE
Lima is the capital of Peru

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#1916]
https://slurp.readthedocs.io/en/latest/lime.html

Remove all references to 'lime'

Files, folders, content.

Add descriptive filenames for images

**Comment by Pritam0077** [comment]
Can you assign me

**Comment by jbampton** [comment]
Good to go thanks 👍

**Comment by Pritam0077** [comment]
In this only I have to change Lime to Lima?

**Comment by jbampton** [comment]
> https://slurp.readthedocs.io/en/latest/lime.html
> 
> Remove all references to 'lime'
> 
> Files, folders, content.
> 
> Add descriptive filenames for images

You must do all this

**Comment by Vishrut19** [comment]
Can you please give me this issue ? @jbampton

**Comment by jbampton** [comment]
Hey @Vishrut19 you are now assigned 👍
