### ISSUE TITLE
Broken YouTube Jedi video

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2047]
Second step of the webdriver code reveals the `jedi` video is broken:

From repo root run:

`ruby drivers/fuchsia.rb`

It should boot up Firefox and run two steps before quitting.

**Comment by jbampton** [comment]
Background picture fails to load as well

**Comment by BaseMax** [comment]
> Background picture fails to load as well

Which picture? link?

**Comment by jbampton** [comment]
https://www.youtube.com/watch?v=esnMDtMysHo

This video does not embed.  Why ?

**Comment by jbampton** [comment]
Runs from here:

https://github.com/slurpcode/slurp/blob/5b922937cd8cdfea1022083eb540ef50d3037d0b/docs/assets/js/eggs.js#L238

I want a new video to embed since the old one is private now

**Comment by smriad** [comment]
@jbampton what is the actual issue here?

**Comment by jbampton** [comment]
Done thanks
