### ISSUE TITLE
Sphinx: "WARNING: 'myst' cross-reference target not found: 'what-is-a-database' [myst.xref_missing]"

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2056]
Some warnings in the Sphinx build

`cd doc; make html`

https://www.sphinx-doc.org/en/master/

**Comment by smriad** [comment]
![Screenshot from 2023-03-09 12-20-20](https://user-images.githubusercontent.com/21966124/223941096-41684aac-c49c-4067-b0f2-51c7a87d7190.png)
Can't reproduce the error in my local @jbampton
