### ISSUE TITLE
Dead links run

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2060]
https://github.com/slurpcode/slurp/actions/runs/4337535110/jobs/7573603278

**Comment by smriad** [comment]
![Screenshot from 2023-03-09 11-46-22](https://user-images.githubusercontent.com/21966124/223931524-515ce3c7-cce6-488c-a629-eeb6b09b3b67.png)
Done

**Comment by jbampton** [comment]
fixed by #2071
