### ISSUE TITLE
App identity seems wrong

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2090]
<img width="1019" alt="Screen Shot 2023-03-21 at 5 44 00 am" src="https://user-images.githubusercontent.com/418747/226449310-457df19c-67d5-4fbd-98f4-4701572b4cfe.png">

**Comment by smriad** [comment]
> <img alt="Screen Shot 2023-03-21 at 5 44 00 am" width="1019" src="https://user-images.githubusercontent.com/418747/226449310-457df19c-67d5-4fbd-98f4-4701572b4cfe.png">

@jbampton how to reproduce the error?

**Comment by jbampton** [comment]
https://slurpcode.github.io/slurp/ Open Developer tools: Application tab: Manifest

<img width="1494" alt="Screen Shot 2023-04-03 at 4 59 28 pm" src="https://user-images.githubusercontent.com/418747/229435238-7f20220a-167b-45ef-862c-5b9998e8228d.png">
