### ISSUE TITLE
Add missing doc: Kurbelspharophon

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2122]
EARLY INSTRUMENTS menu

[24_Kurbelspharophon.pdf](https://github.com/slurpcode/slurp/files/11105889/24_Kurbelspharophon.pdf)

https://slurp.readthedocs.io/

**Comment by aaftab1441** [comment]
Assign this one to me

**Comment by jbampton** [comment]
You only get one issue.  Please stop commenting on every issue !!

**Comment by jbampton** [comment]
For @HadeerAIA maybe ?

**Comment by HadeerAIA** [comment]
Sure, I will see it.

**Comment by HadeerAIA** [comment]
Sure, I will see it.

**Comment by HadeerAIA** [comment]
Sure, I will see it.

**Comment by jbampton** [comment]
@HadeerAIA you are now assigned thanks

**Comment by HadeerAIA** [comment]
Now you can review PR kurbelspharophon #2151 @jbampton
