### ISSUE TITLE
Add another doc: Parametric methods to compare two means

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2123]
MATHEMATICS menu

[Parametric_methods_to_compare_two_means.docx](https://github.com/slurpcode/slurp/files/11106142/Parametric_methods_to_compare_two_means.docx)

https://slurp.readthedocs.io/

**Comment by jbampton** [comment]
Idais is the author

**Comment by jbampton** [comment]
One issue at a time

**Comment by HadeerAIA** [comment]
I can go with this issue, please assign it to me.

**Comment by jbampton** [comment]
Thanks @HadeerAIA you are now assigned

**Comment by jbampton** [comment]
Done. Thanks !!
