### ISSUE TITLE
Add another doc: Fractals

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2124]
MATHEMATICS menu

[fractal_ingles.docx](https://github.com/slurpcode/slurp/files/11106201/fractal_ingles.docx)

https://slurp.readthedocs.io/

Idais is the author

**Comment by aaftab1441** [comment]
Will do this one also

**Comment by janus** [comment]
@jbampton  If not yet assigned . then assign it to me after reviewing my PR.

**Comment by janus** [comment]
@jbampton Please assign to me.

**Comment by jbampton** [comment]
@janus good to go
