### ISSUE TITLE
Add another doc: Law and order Special Victims Unit

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2125]
TELEVISION menu

[Law_and_order_Special_Victims_Unit.docx](https://github.com/slurpcode/slurp/files/11106266/Law_and_order_Special_Victims_Unit.docx)

https://slurp.readthedocs.io/

Author is Harley

**Comment by aaftab1441** [comment]
Also this one

**Comment by jbampton** [comment]
How about you get one pull request merged first before working on multiple issues

**Comment by anufdo** [comment]
Can you please assign me

**Comment by jbampton** [comment]
Hey @anufdo you are now assigned 👍

**Comment by anufdo** [comment]
Please review

**Comment by jbampton** [comment]
Done thanks
