### ISSUE TITLE
Add another doc: Exponential Distribution

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2126]
MATHEMATICS menu

[Exponential_Distribution(1).docx](https://github.com/slurpcode/slurp/files/11106278/Exponential_Distribution.1.docx)

https://slurp.readthedocs.io/

Author is Idais

**Comment by aaftab1441** [comment]
Also this one

**Comment by jbampton** [comment]
We only assign one issue at a time

**Comment by janus** [comment]
@jbampton   Assign this to me , then.
