### ISSUE TITLE
Add another doc: The origin of cinema

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2127]
EASY GOING READING menu

[The_origin_of_cinema.docx](https://github.com/slurpcode/slurp/files/11106304/The_origin_of_cinema.docx)

https://slurp.readthedocs.io/

Author is Idais

**Comment by aaftab1441** [comment]
Also this issue I will work on it.

**Comment by jbampton** [comment]
Hey @aaftab1441 please only work on one issue at a time

**Comment by anufdo** [comment]
can you please assign me

**Comment by jbampton** [comment]
@anufdo good to go 👍
