### ISSUE TITLE
Add another doc: DESCRIPTIVE STATISTICS

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2128]
MATHEMATICS menu

[DESCRIPTIVE_STATISTICS_3.docx](https://github.com/slurpcode/slurp/files/11106325/DESCRIPTIVE_STATISTICS_3.docx)

https://slurp.readthedocs.io/

Author is Idais

**Comment by aaftab1441** [comment]
I will also take this issue kindly assign this to me

**Comment by jbampton** [comment]
Hello @aaftab1441 you are now assigned 👍

**Comment by aaftab1441** [comment]
@jbampton I don't have permissions to push my branch.

**Comment by jbampton** [comment]
Are you working on a fork ?

**Comment by jbampton** [comment]
Thanks
