### ISSUE TITLE
`seek.rb` add option to just print total number of jobs

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2146]
Print jobs total to terminal.

Don't auto open the CSV file.

**Comment by janus** [comment]
@jbampton Assign this one to me. However my Ruby is pretty rusty I may ask some questions on forum or here.  This is important to me because it would be first coding issue I am picking up here.

**Comment by jbampton** [comment]
Hey @anufdo since you have already worked on this script I've assigned you.  Thanks

**Comment by BaseMax** [comment]
@janus best wishes.
Don't worry to work on something new.

**Comment by jbampton** [comment]
Fixed by #2191 thanks
