### ISSUE TITLE
🎣 Add more pre-commit hooks 🎣

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#230]
We already use `overcommit` which is Ruby based for some hooks.
https://github.com/sds/overcommit

Lets look at adding more hooks.  

```
pip install pre-commit-hooks
```

https://github.com/pre-commit/pre-commit-hooks
https://pre-commit.com/hooks.html

refs #204, #222, #227, #229, #232

**Comment by shravanshetty1** [comment]
All the linters currently seem to be in the CI - would like to change them all to be precommit hooks?

**Comment by jbampton** [comment]
We want both.  So we want to keep the linters in the CI as well as have pre-commit hooks.

**Comment by jbampton** [comment]
Done
