### ISSUE TITLE
Seek format "location" column

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2394]
Seems when there is an extended location we need to add space between

![Screenshot from 2023-10-01 00-27-44](https://github.com/slurpcode/slurp/assets/418747/5b44e8d1-9e42-4edf-8e95-46f402016e7d)

**Comment by akssshh** [comment]
Can i work on this?

**Comment by jbampton** [comment]
You are assigned now @akssshh thanks

**Comment by jbampton** [comment]
Hey @akssshh just checking in after a couple of days.

Have you started working ?  Do you need help ?

**Comment by akssshh** [comment]
I've been working on some other projects over a couple of days and made some progress. so I'm in a good place to start working on it soon. thanks for asking!
