### ISSUE TITLE
Fix "Descriptive Statistics"

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2395]
- add author as Idais
- fix layout etc line breaks / markup
- add menu item

https://slurp.readthedocs.io/en/latest/

refs #2128 

[DESCRIPTIVE_STATISTICS_3(1).docx](https://github.com/slurpcode/slurp/files/12777593/DESCRIPTIVE_STATISTICS_3.1.docx)

**Comment by janus** [comment]
@jbampton  Assign this to me.

**Comment by jbampton** [comment]
Hey @janus good to go :+1:
