### ISSUE TITLE
CircleCI mdl step broken

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2403]
https://app.circleci.com/pipelines/github/slurpcode/slurp/7637/workflows/73cfb62b-c8ea-4ecf-91c0-862bd8304c33/jobs/57634

Markdownlint step needs fixing

This uses Ruby mdl gem

**Comment by janus** [comment]
Assign it to me. It would challenge me to learn something new.

**Comment by jbampton** [comment]
Hey @janus you are now assigned thanks
