### ISSUE TITLE
Create new seek "lite" version -> no "salary" or "content" columns; don't open and crawl the full job ad

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#2794]
We already have a lite version so now we need to enhance it.

Lite version should not contain "salary" or "content".

So don't open the full job ad; Move the "check for lite logic" higher up, outside and above: `ad = agent.get(url)`

https://github.com/slurpcode/slurp/blob/e4813ef8a7f9c0cf1a944f17782a289a295f9f87/seek/seek.rb#L276

This will make the lite version faster to crawl

**Comment by jbampton** [comment]
Hey @Dxuian are you interested in this issue ?

**Comment by Dxuian** [comment]
> Hey @Dxuian are you interested in this issue ?

on it

**Comment by jbampton** [comment]
Hey @Dxuian you are now assigned :+1:

**Comment by Dxuian** [comment]
@jbampton  please review #2799
