### ISSUE TITLE
🐙 Convert the GitHub `max per day` shell script to PHP 🐙

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#342]
Need a very basic PHP script that grabs the `max contributions in one day` over the last year from a person's GitHub profile.  To run on the command line.

Ask me any questions.

You can see the example shell scripts here:

https://github.com/fuchsia-programming/fuchsia/tree/master/scrapers/shell

refs #207 

These all do the same thing just slightly differently:

![Screen Shot 2020-01-07 at 10 03 39 am](https://user-images.githubusercontent.com/418747/71858052-7e499280-3135-11ea-97da-38347afc91a2.png)

**Comment by ajakov** [comment]
@jbampton this issue is also done, with pull request #956

**Comment by jbampton** [comment]
Thank you !!
