### ISSUE TITLE
🚧 Convert RST to Markdown 🚧

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#447]
All our new docs in 'Read the Docs' format are in Markdown format except for one page in ReStructuredText format here -> https://github.com/slurpcode/slurp/blob/master/doc/source/markup/xml.rst

Sphinx Python doc generator is being used along with the commonmark extension. 
There is a `requirements.txt` file in the repo root and info on the readme on how to build the docs.

We need to convert that one file to markdown but have an automated way / script / oneliner to do it again in future if needed.

Seems Pandoc can do it, see the chart scroll down says RST to markdown and we are using the recommonmark extension too -> https://pandoc.org/  but there would be other tools too.

https://readthedocs.org/
https://www.sphinx-doc.org/en/master/
https://en.wikipedia.org/wiki/ReStructuredText

**Comment by anisbhsl** [comment]
Submitted #465
