### ISSUE TITLE
🚧 December Code Sprint: Scripting, Travis CI, Linting, Aspell, spell checking on GitHub Actions, Batch files, Sphinx Documentation, pre-commit  🚧

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#600]
http://aspell.net

https://github.com/slurpcode/slurp/blob/master/check-spelling.sh

https://ftp.gnu.org/gnu/aspell/dict/0index.html

https://en.wikipedia.org/wiki/GNU_Aspell

https://github.com/GNUAspell/aspell

Fix bugs in our dictionary, configure additional dictionaries.

Script to sort words in our custom dictionaries - Shell, Ruby, Perl, Python, Golang based

**Comment by jbampton** [comment]
We need Windows batch files to use, similar to the shell scripts. 

Another script https://github.com/slurpcode/slurp/blob/master/check-spelling-single.sh

https://github.com/slurpcode/slurp/blob/1ac28112c8e899d1f13a82f3aa871bff8dc63b19/.circleci/config.yml#L30

Is how we run it on CircleCI  https://circleci.com/

**Comment by jbampton** [comment]
Can be done in PHP too @prestonhunter if you are interested 👍 

We could instead hook it up on Travis CI we are already on there https://travis-ci.org/

Would be good to have another provider on the GitHub Marketplace https://github.com/marketplace

Plus would nice and quick to also get another spell checking implementation on GitHub Actions too :)

https://github.com/features/actions

**Comment by jbampton** [comment]
This should include getting the Travis CI build back up and running and also adding some kind of spell checking on Travis.

https://github.com/slurpcode/slurp/blob/master/.travis.yml   This is our config file not sure if its all working.

We have both a Go and Python basic lint on Travis. Would be good to expand those two linters  / checkers / testers too.

**Comment by jbampton** [comment]
And we need all of this info documented on our Read the Docs site https://slurp.readthedocs.io/en/latest/ in Markdown format.

We use a Python build.  From the root -> cd doc; make html;

Make sure to first install the Python requirements with pip.

https://github.com/slurpcode/slurp/blob/master/requirements.txt

Markdown files goes in `doc/source` and build comes out in `doc/build`

There is an index file `index.rst` for the table of contents etc just add your new page link there somewhere.

We are using Sphinx https://www.sphinx-doc.org/en/master/  -> `Sphinx is a tool that makes it easy to create intelligent and beautiful documentation, written by Georg Brandl and licensed under the BSD license.`

**Comment by jbampton** [comment]
And then finally we need to get a bit smarter about it and use more https://pre-commit.com/

`A framework for managing and maintaining multi-language pre-commit hooks.`

`Git hook scripts are useful for identifying simple issues before submission to code review. We run our hooks on every commit to automatically point out issues in code such as missing semicolons, trailing whitespace, and debug statements. By pointing these issues out before code review, this allows a code reviewer to focus on the architecture of a change while not wasting time with trivial style nitpicks.`

Some of use are already using https://github.com/sds/overcommit 

https://github.com/slurpcode/slurp/blob/1ac28112c8e899d1f13a82f3aa871bff8dc63b19/Gemfile#L38

But i vote we have both overcommit and pre-commit if they work together otherwise I want to move to full pre-commit.

https://github.com/slurpcode/slurp/issues/230

**Comment by BaseMax** [comment]
Hi, you guys

What can I do to help? 

`pre-commit` project have a demo repository. Have look at this, may be useful...
https://github.com/pre-commit/demo-repo#readme

**Comment by BaseMax** [comment]
Hi John,
Where did this issue got? resolved? soon?

**Comment by jbampton** [comment]
Hey @BaseMax I decided to close it down since it was for December. 

I decided GNU Aspell is too much hassle and I am going to use a Golang library called `misspell`.  I am already using it on another project with GitHub Actions

https://github.com/client9/misspell

I still plan to work on the GitHub Actions, Batch files, Sphinx Documentation and the pre-commit.

If you have anything you can offer in those areas it would greatly appreciated 👍
