### ISSUE TITLE
Daredevil avatar for Jim

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#677]
Hey Jorge we need to discuss here in this issue a new GitHub avatar of logo for Jim

https://github.com/slurpcode/slurp/issues/153#issuecomment-720453622

**Comment by summerhill5** [comment]
Ok I can work on this logo.

**Comment by summerhill5** [comment]
Daredevil! what a fun logo... :-D

**Comment by jhomme** [comment]
Hi,

I am asking someone to do this for me because I am blind. Can you attach this to my profile somehow?

Thank you.

Jim

On Nov 2, 2020, at 10:12 AM, Jorge Araica <notifications@github.com> wrote:

﻿
Daredevil! what a fun logo... :-D

**Comment by jbampton** [comment]
Hey @jhomme, Jorge  has done a creative logo for you 

![Daredevil logo 01](https://user-images.githubusercontent.com/418747/97931021-7770c800-1db8-11eb-8f7b-42352bb815c2.jpg)

I will look into getting your new logo / avatar added to your profile 👍

**Comment by jhomme** [comment]
Hi All,
Thank you. I binge watched that show. It was the first TV series I used audio description on, unless it would have. Been Gotham. This put a smile on my face. 



On Nov 2, 2020, at 6:41 PM, John Bampton <notifications@github.com> wrote:

﻿
Hey @jhomme, Jorge has done a creative logo for you



I will look into getting your new logo / avatar added to your profile 👍

**Comment by jhomme** [comment]
Thanks so much all. Lots of fun.
