### ISSUE TITLE
CircleCI build broken

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#733]
Possible cache issue ??

**Comment by jbampton** [comment]
https://app.circleci.com/pipelines/github/slurpcode/slurp/1799/workflows/6371d525-b2b5-43dc-b38b-fe882193db2a/jobs/6703

**Comment by BaseMax** [comment]
Hi John,
Can you explain what I have to do?
I would be happy if I could help.

**Comment by jbampton** [comment]
Hey @BaseMax we just need the CircleCI build to pass green.

Last run was seen here -> https://circleci.com/gh/slurpcode/slurp/6703

Seems like a cache issue ?   Do we need to upgrade the image ?

**Comment by BaseMax** [comment]
I did check this right now.

I see:
```
#!/bin/bash -eo pipefail
bundle exec rubocop
```

**Could not find fileutils-1.5.0 in any of the sources**
Run `bundle install` to install missing gems.


Update: maybe useful? https://stackoverflow.com/a/26231894/10096230

**Comment by BaseMax** [comment]
> Possible cache issue ??

Yes probably, remove vendor cache and retry to install bundle again...

**Comment by jbampton** [comment]
Fixed by #754
