### ISSUE TITLE
Add article on casino gaming to the Read the Docs site

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#762]
How to Really Enjoy Casino Gaming

First things first - Why should you listen to me? I worked on casino floors, in operations,
technical, and regulatory positions, talking with gamblers for 21 years. I’ve heard it (and seen
it) all. I know how things work in the business but I was not a manager, so people were quite
open with me.

The reality is that you will probably NOT win. You KNOW this! Casinos must make a profit to
be able to provide you with all of the atmosphere that you enjoy, so they will take more than
they give. But to keep you coming back, they must make that enjoyable atmosphere
compelling, so just be aware that the whole idea is to make the experience addictive.

You will be treated to some small wins from time to time, and to lots of exciting sights and
sounds, entertainment, Woo Hoo! Good food will be available, and many of the employees
will be attractive and charming, whether you are a man or a woman. Some folks will win BIG
and there will be lots of noise and employees congratulating them, but in the long run YOU will
probably lose. THAT is a fact but the key word is probably. Because you know that, the
atmosphere is designed to make you think YOU will be the next winner.

The key for you is to enjoy all that the casino is providing and treat it like any other
entertainment experience. Before you leave the house, you normally decide how much you
will be spending, right? Are you going to a movie or to a Broadway play, to McDonalds or to a
French restaurant with wait staff in dress clothes? Make that spending decision and stick to it.

Since the casino offers a “McDonalds plan” and/or a “Four Seasons plan” you can customize
your own experience but YOU must make the decision. You can play nickel slots or dollar slots.
You can play Black Jack or sit at a high stakes poker table. The dealer will give you sexy looks
possibly. Often you can enjoy live music or a floor show, your choice, but stick to your plan!

Oh yeah, you can drink any grade of alcohol you want as well. Be careful - DUH! If you stick to
your plan, well, you’ll be able to afford to do it again someday soon. Just keep in mind that
what you’re enjoying is the ENTERTAINMENT, not a guarantee or even the likelihood of a big
win.

I knew a blue collar, hard working motorcycle club member who lost his home, and a very nice,
normal, married algebra teacher who lost her home. If it can happen to them, it can happen
to you, so decide what you can afford and go out for that kind of evening, lunch, or whatever,
but stick to the plan and be happy with the entertainment that you get.

You might even meet other people whose company you enjoy, people who enjoy activities
other than gambling. Hey, maybe you can all go water skiing, bowling, or something…..

**Comment by ClayLanzino** [comment]
Hi John, very interesting article. Thanks for sharing. 
PS I am training in Coderwars, in order to strengthen my Python skills, waiting for any task.  I really want to stop looking  for jobs all day long on Upwork.

**Comment by ClayLanzino** [comment]
Hello Harley, very interesting article. Thanks for sharing.

**Comment by jbampton** [comment]
Fixed by #754

**Comment by grfxwzdesigner** [comment]
And thank you Clay!  I'm glad you found it interesting.  I had thousands of conversations with customers in the casinos I've worked in, met some really interesting and nice people.
