### ISSUE TITLE
Three dead links

### ISSUE THREAD

**Issue by jbampton** [slurpcode/slurp#798]
ERROR: 3 dead links found!
[✖] http://brewformulas.org/Python3 → Status: 404
[✖] http://brewformulas.org/Perl → Status: 404
[✖] http://brewformulas.org/Cloc → Status: 404

**Comment by jbampton** [comment]
Thank you.  Fixed now 👍

**Comment by smriad** [comment]
> Thank you. Fixed now 👍
Glad to help. Thanks
